# Generated by Django 5.0.4 on 2024-05-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastfood',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
