# Generated by Django 5.0.4 on 2024-06-13 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_fastfood_about_alter_fastfood_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fastfood',
            name='about',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fastfood',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
