# Generated by Django 5.0.4 on 2024-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_savedrecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='saved_recipes',
            new_name='saved_recipes_fastfood',
        ),
        migrations.RemoveField(
            model_name='savedrecipe',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_recipes_savedrecipe',
            field=models.ManyToManyField(related_name='saved_by', to='recipe.savedrecipe'),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='meal_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_label',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='source',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
