# Generated by Django 5.0.4 on 2024-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0009_remove_userprofile_saved_recipes_fastfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_url',
            field=models.URLField(max_length=500),
        ),
    ]
