# Generated by Django 5.0.4 on 2024-07-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_savedrecipe_recipe_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedrecipe',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='meal_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='recipe_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='savedrecipe',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
